import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'

const require = createRequire(import.meta.url)
const root = dirname(dirname(fileURLToPath(import.meta.url)))
const lib = join(root, 'lib')
await mkdir(lib, { recursive: true })

// The client bundle MUST self-register under the exact package name. DSH keys
// its client-module manifest by the package specifier and rejects a bundle
// whose declared id differs (a scoped package registering under a short name
// collides and fails web boot with
// "client-modules: duplicate factory registration for ...").
const { name: moduleId } = JSON.parse(await readFile(join(root, 'package.json'), 'utf8'))

await copyFile(join(root, 'src', 'index.cjs'), join(lib, 'index.cjs'))
await copyFile(join(root, 'src', 'core.cjs'), join(lib, 'core.cjs'))
await copyFile(join(root, 'src', 'optimizer-template.cjs'), join(lib, 'optimizer-template.cjs'))
await copyFile(join(root, 'src', 'features.cjs'), join(lib, 'features.cjs'))
await copyFile(join(root, 'src', 'default-few-shot-library.json'), join(lib, 'default-few-shot-library.json'))
const createClientPlugin = require('../src/client-factory.cjs')
const factory = createClientPlugin.toString()
const client = `// GENERATED by scripts/build.mjs — edit src/client-factory.cjs instead.\nwindow.__ModuleLoader__.load({\n  id: ${JSON.stringify(moduleId)},\n  factory: (require) => {\n    var module = { exports: {} }; var exports = module.exports;\n    const React = require("react");\n    const createClientPlugin = (${factory});\n    module.exports = createClientPlugin(React);\n    return module.exports;\n  },\n});\n`
await writeFile(join(lib, 'client.cjs'), client, 'utf8')

const generated = await readFile(join(lib, 'client.cjs'), 'utf8')
if (!generated.includes('window.__ModuleLoader__.load')) {
  throw new Error('client bundle wrapper was not generated')
}
if (!generated.includes(`id: ${JSON.stringify(moduleId)}`)) {
  throw new Error(`client bundle id does not match package name "${moduleId}"`)
}

